# Generated by Django 5.2.17 on 2026-08-31 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionalsection',
            name='entity',
        ),
        migrations.DeleteModel(
            name='PromotionalCampaign',
        ),
        migrations.DeleteModel(
            name='PromotionalSection',
        ),
    ]
