# Generated by Django 5.2.17 on 2026-09-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_remove_promotionalsection_entity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
    ]
