# Generated by Django 5.2.17 on 2026-09-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_delete_featuredproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('youtube', 'YouTube Video')], default='image', help_text='Select the type of media for this banner.', max_length=10),
        ),
        migrations.AddField(
            model_name='banner',
            name='video_file',
            field=models.FileField(blank=True, help_text="Upload an MP4 or WebM video file (if media type is 'Video'). Recommended max size: 20MB.", null=True, upload_to='banner_videos/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='video_url',
            field=models.URLField(blank=True, help_text="Enter a YouTube or Vimeo URL (if media type is 'YouTube Video'). Example: https://www.youtube.com/watch?v=VIDEO_ID"),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text="Recommended size: 1920 x 650 px. Upload an image (if media type is 'Image').", null=True, upload_to='banners/'),
        ),
    ]
