# Generated by Django 5.2.17 on 2026-09-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_thingwedo_cybersecuritysolution_project_blogpost'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='banners_blo_entity__34f1fd_idx',
            old_name='banners_blo_entity__idx',
        ),
        migrations.RenameIndex(
            model_name='cybersecuritysolution',
            new_name='banners_cyb_entity__2293cc_idx',
            old_name='banners_cyb_entity__idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='banners_pro_entity__e28a1e_idx',
            old_name='banners_pro_entity__proj_idx',
        ),
        migrations.RenameIndex(
            model_name='thingwedo',
            new_name='banners_thi_entity__5c9b7d_idx',
            old_name='banners_thi_entity__idx',
        ),
    ]
