# Generated by Django 5.2.17 on 2026-09-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0021_banner_remove_entity_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='entities',
            field=models.ManyToManyField(help_text='Select one or more entities this banner belongs to.', related_name='banners', to='banners.entity', verbose_name='Entities'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['is_active', 'display_order'], name='banners_ban_is_acti_66e158_idx'),
        ),
    ]
