# Generated by Django 5.2.17 on 2026-09-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0023_remove_banner_banners_ban_entity__73670f_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='banner',
            name='banners_ban_entity__73670f_idx',
        ),
    ]
