# Generated by Django 5.2.17 on 2026-09-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0025_banner_revert_entities_m2m_to_entity_fk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomepageGif',
        ),
    ]
