# Generated by Django 5.2.17 on 2026-09-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0026_delete_homepagegif'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, help_text='URL of this product on the Promallshop website.'),
        ),
    ]
